export const moduloNames = {
   HOME: 'HOME',
   PERFIL: 'PERFIL',
   ACTIVIDADES: 'ACTIVIDADES',
   LINEAMIENTOS: 'LINEAMIENTOS',
   PROCESOS: 'PROCESOS',
   UTILIDADES: 'UTILIDADES',
   GESTION_TRAMITES: 'GESTIÓN TRÁMITES',
   REPORTES: 'REPORTES'
}

export const subModuloNames = {
   REGISTRAR_PRODUCCION: 'REGISTRAR PRODUCCIÓN',
   NUEVA_ACTIVIDAD: 'NUEVA ACTIVIDAD',
   NUEVO_INTERPOL: 'NUEVO INTERPOL',
   NUEVO_OPERATIVO: 'NUEVO OPERATIVO',
   NUEVO_EXPEDIENTE_MININTER: 'NUEVO EXPEDIENTE MININTER',
   NUEVO_OFICIO: 'NUEVO OFICIO',
   NUEVA_CEREMONIA: 'NUEVA CEREMONIA',
   NUEVO_EXPEDIENTE_SFM: 'NUEVO EXPEDIENTE SFM',
   BUSCAR_INTERPOL: 'BUSCAR INTERPOL',
   BUSCAR_OPERATIVO: 'BUSCAR OPERATIVO',
   BUSCAR_PRE_INSCRIPCION: 'BUSCAR PREINSCRIPCIÓN',
   BUSCAR_REFUGIADO: 'BUSCAR REFUGIADO',
   REPORTE_MESA_DIGITAL: 'REPORTE MESA DIGITAL',
   REPORTE_OPERATIVOS: 'REPORTE OPERATIVOS',
   REPORTE_PRODUCCION: 'REPORTE PRODUCCION',
   REPORTE_NACIONALIZACION: 'REPORTE NACIONALIZACIÓN',
   REPORTE_EXPEDIENTES_MININTER: 'REPORTE EXPEDIENTES MININTER',
   ASIGNAR_EXPEDIENTES_NAC: 'ASIGNAR EXPEDIENTES NACIONALIZACIÓN',
   EVALUAR_EXPEDIENTE_NAC: 'EVALUAR EXPEDIENTE NACIONALIZACIÓN',
   RECEPCION_Y_ASIGNACION_SFM: 'RECEPCIÓN Y ASIGNACIÓN SFM',
   EVALUACION_EXPEDIENTES_SFM: 'EVALUACIÓN DE EXPEDIENTES SFM',
   DEPURACION_DATOS: 'DEPURACIÓN DE DATOS',
   ANALISIS_INFORMACION: 'ANALISIS DE INFORMACIÓN',
   ASIGNAR_EXTRACCION: 'ASIGNAR EXTRACCIÓN',
   EXTRACCION_DATOS: 'EXTRACCIÓN DE DATOS',
   BUSCAR_DNV: 'BUSCAR DNV'
}

export const componentsType = {
   MODULO: 'MODULO',
   SUB_MODULO: 'SUB_MODULO',
   ITEM: 'ITEM',
   SUB_ITEM: 'SUB_ITEM'
}
