export * from './tipoDocumento'
export * from './organigrama'
export * from './tipoLogico'
export * from './grupo'
export * from './añosControlMigratorio'
export * from './jornadaLaboral'
export * from './regimenLaboral'
export * from './tipoLicencia'
