import { MySelectItem } from 'components'

export const tipoLicencia: MySelectItem[] = [
   { label: 'LICENCIA POR SALUD (CERTIFICADO DE INCAPACIDAD - CITT O CERTIF. MED.)', value: 'LICENCIA POR SALUD (CERTIFICADO DE INCAPACIDAD - CITT O CERTIF. MED.)' },
   { label: 'LICENCIA POR ASUNTOS PARTICULARES', value: 'LICENCIA POR ASUNTOS PARTICULARES' },
   { label: 'LICENCIA POR ENFERMEDAD GRAVE DE FAMILIAR DIRECTO', value: 'LICENCIA POR ENFERMEDAD GRAVE DE FAMILIAR DIRECTO' },
   { label: 'LICENCIA POR ONOMASTICO', value: 'LICENCIA POR ONOMASTICO' },
   { label: 'LICENCIA POR FALLECIMIENTO DE FAMILIAR DIRECTO', value: 'LICENCIA POR FALLECIMIENTO DE FAMILIAR DIRECTO' },
   { label: 'LICENCIA POR COMISION DEL SERVICIO', value: 'LICENCIA POR COMISION DEL SERVICIO' },
   { label: 'LICENCIA POR COMPENSACION DE HORAS EXTRAORDINARIAS NO REMUNERADAS', value: 'LICENCIA POR COMPENSACION DE HORAS EXTRAORDINARIAS NO REMUNERADAS' },
   { label: 'PERMISO POR COMPENSACION DE HORAS EXTRAORDINARIAS NO REMUNERADAS', value: 'PERMISO POR COMPENSACION DE HORAS EXTRAORDINARIAS NO REMUNERADAS' },
   { label: 'PERMISO POR ASUNTOS PARTICULARES', value: 'PERMISO POR ASUNTOS PARTICULARES' },
   { label: 'PERMISO PARA EJERCER DOCENCIA', value: 'PERMISO PARA EJERCER DOCENCIA' },
   { label: 'PERMISO POR CAPACITACION', value: 'PERMISO POR CAPACITACION' },
   { label: 'PERMISO POR CITACION EXPRESA (PNP, JUDICIAL etc)', value: 'PERMISO POR CITACION EXPRESA (PNP, JUDICIAL etc)' },
   { label: 'PERMISO POR COMISION DEL SERVICIO', value: 'PERMISO POR COMISION DEL SERVICIO' },
   { label: 'PERMISO POR ATENCION MEDICA ACREDITADA (PREVIA CITA)', value: 'PERMISO POR ATENCION MEDICA ACREDITADA (PREVIA CITA)' },
   { label: 'OTROS', value: 'OTROS' }

]
