export type LocalStorageKey =
   | ''
   | 'ANALIZAR_EXTRACCION_BANDEJA_ENTRADA_NRO_PAGINA'
   | 'ANALIZAR_EXTRACCION_BANDEJA_ANALISIS_NRO_PAGINA'
   | 'RPT_PRODUCCION_DIARIO_NRO_PAGINA'
   | 'BUSCAR_INTERPOL_NRO_PAGINA'
   | 'BUSCAR_DNV_NRO_PAGINA'
   | 'CONTROL_CALIDAD_BANDEJA_CTRLCAL_NROPAG'
